spring:
  application:
    name: sanjin-backend-init
    # 数据库链接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: root
server:
  port: 8080

##